
package formation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RecensementImplService", targetNamespace = "http://formation/", wsdlLocation = "http://10.130.10.6:9999/ws/recensement?wsdl")
public class RecensementImplService
    extends Service
{

    private final static URL RECENSEMENTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RECENSEMENTIMPLSERVICE_EXCEPTION;
    private final static QName RECENSEMENTIMPLSERVICE_QNAME = new QName("http://formation/", "RecensementImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.130.10.6:9999/ws/recensement?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECENSEMENTIMPLSERVICE_WSDL_LOCATION = url;
        RECENSEMENTIMPLSERVICE_EXCEPTION = e;
    }

    public RecensementImplService() {
        super(__getWsdlLocation(), RECENSEMENTIMPLSERVICE_QNAME);
    }

    public RecensementImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECENSEMENTIMPLSERVICE_QNAME, features);
    }

    public RecensementImplService(URL wsdlLocation) {
        super(wsdlLocation, RECENSEMENTIMPLSERVICE_QNAME);
    }

    public RecensementImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECENSEMENTIMPLSERVICE_QNAME, features);
    }

    public RecensementImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecensementImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RecensementImpl
     */
    @WebEndpoint(name = "RecensementImplPort")
    public RecensementImpl getRecensementImplPort() {
        return super.getPort(new QName("http://formation/", "RecensementImplPort"), RecensementImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecensementImpl
     */
    @WebEndpoint(name = "RecensementImplPort")
    public RecensementImpl getRecensementImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://formation/", "RecensementImplPort"), RecensementImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECENSEMENTIMPLSERVICE_EXCEPTION!= null) {
            throw RECENSEMENTIMPLSERVICE_EXCEPTION;
        }
        return RECENSEMENTIMPLSERVICE_WSDL_LOCATION;
    }

}
