
package fr.poec.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RecensementImpl", targetNamespace = "http://soap.poec.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RecensementImpl {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "jeMeDeclare", targetNamespace = "http://soap.poec.fr/", className = "fr.poec.soap.JeMeDeclare")
    @ResponseWrapper(localName = "jeMeDeclareResponse", targetNamespace = "http://soap.poec.fr/", className = "fr.poec.soap.JeMeDeclareResponse")
    @Action(input = "http://soap.poec.fr/RecensementImpl/jeMeDeclareRequest", output = "http://soap.poec.fr/RecensementImpl/jeMeDeclareResponse")
    public void jeMeDeclare(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
